#!/usr/bin/env python3
"""
Project the design-commitment MOVE MENU from schemas/script.primitives.v3.json.

The menu is the governed list of instructional moves handed to stopping point 3
(agents/_studio/03_design_commitment.md) as an INPUT, beside the digest and memo. The prompt
itself stays verbatim (studio rule 2); the menu is what makes its choices land on governed names.

The schema is canon; the menu is a projection. It is generated from each type's `x-menu`
annotation, its required fields, and the `x-candidate-crosswalk` — never hand-edited.

    python3 tools/project_move_menu.py           # (re)write the menu
    python3 tools/project_move_menu.py --check   # exit 1 if the committed menu is stale
"""
import argparse, json, sys
from pathlib import Path

CORE = Path(__file__).resolve().parent.parent
SCHEMA = CORE / "schemas" / "script.primitives.v3.json"
OUT = CORE / "agents" / "_studio" / "03_design_commitment" / "move_menu.md"


def render(schema):
    defs = schema["$defs"]
    union = [r["$ref"].split("/")[-1] for r in defs["primitive"]["oneOf"]]
    L = []
    L.append("<!-- GENERATED by tools/project_move_menu.py from schemas/script.primitives.v3.json."
             " Do not edit by hand; change the schema and re-run. -->")
    L.append("")
    L.append("# Instructional move menu (script.primitives.v3)")
    L.append("")
    L.append("*An input to stopping point 3, `03_design_commitment.md`. Paste it in with the digest and "
             "the exploration memo. The prompt runs verbatim; this menu is the governed vocabulary its "
             "choices should land on.*")
    L.append("")
    L.append("**How to use it.** Where a scene or beat does one of these jobs, name the move in the "
             "script, e.g. `[move: worked_example]`. If a scene needs a move that isn't here, name it "
             "in plain words and list it under DESIGN COMMITMENT NOTES as **ungoverned**. The list is "
             "closed, so a new move goes in through a version bump, never by being slipped in.")
    L.append("")
    L.append("| Move | Use when | Not for | Must carry |")
    L.append("|---|---|---|---|")
    for k in union:
        d = defs[k]
        m = d["x-menu"]
        req = ", ".join(f"`{f}`" for f in d.get("required", []) if f != "type") or "—"
        L.append(f"| **{m['label']}** `{k}` | {m['use_when']} | {m['not_for']} | {req} |")
    L.append("")
    scen = defs.get("scenario")
    if scen:
        L.append("## Scenario variants")
        L.append("")
        L.append(scen["properties"]["variant"]["description"])
        L.append("")
    cw = schema.get("x-candidate-crosswalk") or {}
    if cw:
        L.append("## Where the 2026-09-25 candidates landed")
        L.append("")
        L.append("| Candidate | Lands as |")
        L.append("|---|---|")
        for name, v in cw.items():
            if name.startswith("_"):
                continue
            if "type" in v:
                how = f" ({v['how']})" if v.get("how") else ""
                L.append(f"| {name} | `{v['type']}`{how} |")
            else:
                L.append(f"| {name} | *not a move*: {v['routed']}. {v['why']} |")
        L.append("")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render(json.loads(SCHEMA.read_text(encoding="utf-8")))
    if a.check:
        cur = OUT.read_text(encoding="utf-8").replace("\r\n", "\n") if OUT.exists() else None
        if cur != text:
            print(f"STALE: {OUT.relative_to(CORE)} does not match the schema; re-run without --check")
            sys.exit(1)
        print(f"CURRENT: {OUT.relative_to(CORE)}")
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(CORE)}")


if __name__ == "__main__":
    main()
